import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import type { ReactNode } from "react";
import { Suspense } from "react";
import Header from "../components/Header";
import Providers from "./Providers";
import Navbar from "../components/Navbar";
import SearchBox from "../components/SearchBox";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dawit IMDB",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          {/* ✅ Wrap all client components inside Suspense */}
          <Suspense fallback={<div className="text-center p-6">Loading header...</div>}>
            <Header />
          </Suspense>

          <Suspense fallback={<div className="text-center p-6">Loading navbar...</div>}>
            <Navbar />
          </Suspense>

          <Suspense fallback={<div className="text-center p-6">Loading search...</div>}>
            <SearchBox />
          </Suspense>

          {children}
        </Providers>
      </body>
    </html>
  );
}
